### ISSUE TITLE
Images inside post's body

### ISSUE THREAD

**Issue by matheusfavieira** [jacurtis/laravel-blog-tutorial#13]
This new post form is able to upload a single cover image.

I would like to know if you know how to insert multiple images inside the post's body using that text editor or if has another which you recommend (for example this text editor used by github, is possible drag and drop files).

If it's possible, how I should save the images?

Thanks in advanced.

**Comment by steve5287** [comment]
Hey well that's possible but not this way, we are uploading images from a file input "single file" so to upload more than 1 you will need the laravel file manager or another one.. That way you will be able to select multiple images and post them there. Works with jquery i think not sure.

**Comment by jacurtis** [comment]
This tutorial wasn't really organized to upload multiple files. It is very possible, but wasn't provided in the tutorial. You would need to create a database table to store the image paths and metadata.
We will make a tutorial at some point to demonstrate this, but going to close this issue because it isn't really a bug and this repo isnt open for new features (because I am trying to keep it stable with the releases in the videos).

Thanks for submitting the interest in this feature and we can address it on future videos on the channel. Make sure you are subscribed! Thanks.
