### ISSUE TITLE
Php artisan not working 

### ISSUE THREAD

**Issue by prakharBDev** [jacurtis/laravel-blog-tutorial#7]
After i download the source code 
I ca'nt be able to use the php artisan serve 
what to do ?

**Comment by DevinNorgarb** [comment]
Have you done a composer install first?

**Comment by prakharBDev** [comment]
yeah i have composer

**Comment by prakharBDev** [comment]
actually i was building it while watching but now i found the full source code so  chose to download the whole code so i can analyse it but it's not working

**Comment by DevinNorgarb** [comment]
Yes but have you typed composer install in the command line? Artisan wont
run without the command 'composer install'  being run first.

**Comment by prakharBDev** [comment]
but command is working in "my" project which i was building previously, it is giving me a missing file error in bootstrap folder

**Comment by prakharBDev** [comment]
after composer install it's not giving me error but still not working it's giving me a whoop's something went wrong msg

**Comment by DevinNorgarb** [comment]
make sure you have your .env file in the root directory

in the command line run without the quotes " cp .env.example .env " on
linux. not sure about windows but
just make sure there is a .env file present.

**Comment by jacurtis** [comment]
If you are pulling code from the repo then you need to do a few things to get started.
1. Run `composer install`
2. Run `yarn` if you have **Yarn**, otherwise `npm install` if you have **NPM**
3. Run `php artisan storage:link`
4. Run `cp .env.example .env` (this will make your sample `.env` file)
5. Edit your new `.env` file and update it with relevant information such as your Database credentials and SMTP server
6. Run `php artisan key:generate` _to generate your key_
7. Run `chmod -R  775 storage boostrap/cache` _(to set permissions that Laravel needs for these folders)_

After you do those things it should work as expected.
